spring:
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  application:
    name: solved-service
  config:
    activate:
      on-profile: dev

scheduler:
  cron:
    member: "30 33 23 * * *"
    study: "30 17 10 * * *"
    lastSolved: "30 39 21 * * *"

