#spring:
#  application:
#    name: config-solved-dev
#  config:
#    import: optional:configserver:http://ec2-3-39-24-149.ap-northeast-2.compute.amazonaws.com:8080/
#  batch:
#    jdbc:
#      initialize-schema: always
#    job:
#      enabled: true
#      name: ${job.name:solved}

spring:
  batch:
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: baeker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      linger:
        ms: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/solved_table?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor




message:
  topic:
    name: "solved"


scheduler:
  cron:
    member: "0 */3 * * * *"
    study: "0 */5 * * * *"

