spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(kP70B7pgHyMUq+ktxo0RVUNgfN4xFBpXoRGIUsOj9/y7cNVzOPE83jZp52k35giaAKx8f8vXCDxbTOU/1uLO89kUDCtoma7dfybxmZIDk9ueBmyCQS4xcdtVFsnG+HEp3wcQjJ5TyenMpPf+Ms6BIQeSITBgj8msN6yy9A1c35GjO92/sSbIQ+OggtYyhB5F)
    username: ENC(plDde76MscNwKMt9v4A6Rw==)
    password: ENC(OH+qshDPtFh1h1gDdWExzz/t0BlOzVbo)
  kafka:
    bootstrap-servers: ${custom.server}:9092
    consumer:
      group-id: solved
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      linger:
        ms: 10

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: warn

scheduler:
  cron:
    member: "0 0 18 * * *"
    study: "0 0 19 * * *"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${custom.server}:8761/eureka/

custom:
  server: ENC(0zWdK1NtpOSg0B/P5gqfGe+3WBULxDvm)