spring:
  application:
    name: config-dev
  config:
    import: optional:configserver:http://ec2-3-39-24-149.ap-northeast-2.compute.amazonaws.com:8080

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/solved?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root #ENC(MrlF9UZUaHufCgWLRE3ipQ==)
    password: 1234 #ENC(dhw6nRBS+50xHhqPVFnZdw==)

scheduler:
  cron:
    member: "0 */3 * * * *"
    study: "0 */5 * * * *"
    pull: "0 */2 * * * *"