spring:
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  application:
    name: solved
  profiles:
    default: dev
  batch:
    jdbc:
      initialize-schema: always
  kafka:
    bootstrap-servers: 34.22.94.177:19092 # TODO: kafka 서버 주소나오면 입력
    consumer:
      group-id: solved
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      linger:
        ms: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/solved_table?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

#eureka:
#  instance:
#    instance-id: ${custom.server}:${server.port}
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://${custom.server}:8761/eureka/




server:
  port: 8084




message:
  topic:
    studyRule: "studyRule"
    member: "member"
    solved: "solved-member"


scheduler:
  cron:
    member: "0 */3 * * * *"
    study: "0 */5 * * * *"
    lastSolved: "30 37 21 * * *"

#custom:
#  server: http://localhost:9000
custom:
  server: https://34.64.245.180 # Gateway 주소
  port: :443